import type { KeigoVerbRow } from "@/types/work";

export const keigoVerbRows: KeigoVerbRow[] = [
  {
    id: "suru",
    label: "する",
    plain: { text: "する" },
    teineigo: { text: "します" },
    sonkeigo: { text: "なさる", ruby: [{ text: "な", reading: "な" }] },
    kenjougo: { text: "いたす", ruby: [{ text: "致", reading: "いた" }] },
  },
  {
    id: "iku",
    label: "行く",
    labelRuby: [{ text: "行", reading: "い" }],
    plain: { text: "行く", ruby: [{ text: "行", reading: "い" }] },
    teineigo: { text: "行きます", ruby: [{ text: "行", reading: "い" }] },
    sonkeigo: { text: "いらっしゃる" },
    kenjougo: { text: "伺う", ruby: [{ text: "伺", reading: "うかが" }] },
  },
  {
    id: "kuru",
    label: "来る",
    labelRuby: [{ text: "来", reading: "く" }],
    plain: { text: "来る", ruby: [{ text: "来", reading: "く" }] },
    teineigo: { text: "来ます", ruby: [{ text: "来", reading: "き" }] },
    sonkeigo: { text: "いらっしゃる" },
    kenjougo: { text: "参る", ruby: [{ text: "参", reading: "まい" }] },
  },
  {
    id: "iu",
    label: "言う",
    labelRuby: [{ text: "言", reading: "い" }],
    plain: { text: "言う", ruby: [{ text: "言", reading: "い" }] },
    teineigo: { text: "言います", ruby: [{ text: "言", reading: "い" }] },
    sonkeigo: { text: "おっしゃる" },
    kenjougo: { text: "申し上げる", ruby: [{ text: "申", reading: "もう" }, { text: "上", reading: "あ" }] },
  },
  {
    id: "miru",
    label: "見る",
    labelRuby: [{ text: "見", reading: "み" }],
    plain: { text: "見る", ruby: [{ text: "見", reading: "み" }] },
    teineigo: { text: "見ます", ruby: [{ text: "見", reading: "み" }] },
    sonkeigo: { text: "ご覧になる", ruby: [{ text: "覧", reading: "らん" }] },
    kenjougo: { text: "拝見する", ruby: [{ text: "拝見", reading: "はいけん" }] },
  },
  {
    id: "kiku",
    label: "聞く",
    labelRuby: [{ text: "聞", reading: "き" }],
    plain: { text: "聞く", ruby: [{ text: "聞", reading: "き" }] },
    teineigo: { text: "聞きます", ruby: [{ text: "聞", reading: "き" }] },
    sonkeigo: { text: "お聞きになる", ruby: [{ text: "聞", reading: "き" }] },
    kenjougo: { text: "伺う", ruby: [{ text: "伺", reading: "うかが" }] },
  },
  {
    id: "taberu",
    label: "食べる",
    labelRuby: [{ text: "食", reading: "た" }],
    plain: { text: "食べる", ruby: [{ text: "食", reading: "た" }] },
    teineigo: { text: "食べます", ruby: [{ text: "食", reading: "た" }] },
    sonkeigo: { text: "召し上がる", ruby: [{ text: "召", reading: "め" }, { text: "上", reading: "あ" }] },
    kenjougo: { text: "いただく" },
  },
  {
    id: "iru",
    label: "いる",
    plain: { text: "いる" },
    teineigo: { text: "います" },
    sonkeigo: { text: "いらっしゃる" },
    kenjougo: { text: "おる" },
  },
  {
    id: "morau",
    label: "もらう",
    plain: { text: "もらう" },
    teineigo: { text: "もらいます" },
    sonkeigo: { text: "ください" },
    kenjougo: { text: "いただく" },
  },
  {
    id: "ageru",
    label: "あげる",
    plain: { text: "あげる" },
    teineigo: { text: "あげます" },
    sonkeigo: { text: "—" },
    kenjougo: { text: "差し上げる", ruby: [{ text: "差", reading: "さ" }, { text: "上", reading: "あ" }] },
  },
  {
    id: "shiru",
    label: "知る",
    labelRuby: [{ text: "知", reading: "し" }],
    plain: { text: "知る", ruby: [{ text: "知", reading: "し" }] },
    teineigo: { text: "知ります", ruby: [{ text: "知", reading: "し" }] },
    sonkeigo: { text: "ご存じ", ruby: [{ text: "存", reading: "ぞん" }] },
    kenjougo: { text: "存じる", ruby: [{ text: "存", reading: "ぞん" }] },
  },
  {
    id: "au",
    label: "会う",
    labelRuby: [{ text: "会", reading: "あ" }],
    plain: { text: "会う", ruby: [{ text: "会", reading: "あ" }] },
    teineigo: { text: "会います", ruby: [{ text: "会", reading: "あ" }] },
    sonkeigo: { text: "お会いになる", ruby: [{ text: "会", reading: "あ" }] },
    kenjougo: { text: "お目にかかる", ruby: [{ text: "目", reading: "め" }] },
  },
];
