import type { WorkPageContent, WorkPhrase } from "@/types/work";

const emailOpenInternal: WorkPhrase[] = [
  {
    id: "k-email-o1",
    japanese: "お疲れ様です。〇〇部の〇〇です。",
    romaji: "Otsukaresama desu. ○○-bu no ○○ desu.",
    english: "Good afternoon / thanks for your work — this is ○○ from ○○ department.",
    register: "Internal · polite (です・ます)",
    usage: "Default internal mail opening same day; not for first contact with executives you have never met.",
  },
  {
    id: "k-email-o2",
    japanese: "ご多忙のところ恐れ入ります。",
    ruby: [{ text: "多忙", reading: "たぼう" }],
    romaji: "Go-tabō no tokoro osore irimasu.",
    english: "Sorry to contact you while you are busy.",
    register: "Internal · humble (team / upward)",
    usage: "Before a request upward; skip with close peers if they prefer short mail.",
  },
  {
    id: "k-email-o3",
    japanese: "平素より大変お世話になっております。",
    ruby: [{ text: "平素", reading: "へいそ" }, { text: "世話", reading: "せわ" }],
    romaji: "Heiso yori taihen o-sewa ni natte orimasu.",
    english: "Thank you as always for your kind support.",
    register: "Client · humble",
    usage: "Standard opening to external clients; pair with company name in the next line.",
  },
  {
    id: "k-email-o4",
    japanese: "突然のご連絡失礼いたします。",
    ruby: [{ text: "突然", reading: "とつぜん" }, { text: "失礼", reading: "しつれい" }],
    romaji: "Totsuzen no go-renraku shitsurei itashimasu.",
    english: "Forgive this sudden message.",
    register: "Client · humble",
    usage: "First mail to a new external contact or after a long silence.",
  },
  {
    id: "k-email-o5",
    japanese: "いつもお世話になっております。",
    romaji: "Itsumo o-sewa ni natte orimasu.",
    english: "Thank you for your continued support.",
    register: "Client · polite",
    usage: "Slightly lighter than 平素より; common with vendors you mail weekly.",
  },
];

const emailCloseInternal: WorkPhrase[] = [
  {
    id: "k-email-c1",
    japanese: "以上、よろしくお願いいたします。",
    ruby: [{ text: "以上", reading: "いじょう" }],
    romaji: "Ijō, yoroshiku onegai itashimasu.",
    english: "That is all — thank you in advance.",
    register: "Internal · polite (です・ます)",
    usage: "Standard internal close when asking for action.",
  },
  {
    id: "k-email-c2",
    japanese: "ご確認のほど、よろしくお願いいたします。",
    ruby: [{ text: "確認", reading: "かくにん" }],
    romaji: "Go-kakunin no hodo, yoroshiku onegai itashimasu.",
    english: "I would appreciate your confirmation.",
    register: "Internal · humble (team / upward)",
    usage: "When you need approval or a read receipt on a decision.",
  },
  {
    id: "k-email-c3",
    japanese: "何卒よろしくお願い申し上げます。",
    ruby: [{ text: "何卒", reading: "なにとぞ" }, { text: "申", reading: "もう" }],
    romaji: "Nanitozo yoroshiku onegai mōshiagemasu.",
    english: "I humbly ask for your cooperation.",
    register: "Client · humble",
    usage: "Formal client close — stronger than よろしくお願いします.",
  },
  {
    id: "k-email-c4",
    japanese: "お手数をおかけしますが、何卒よろしくお願いいたします。",
    ruby: [{ text: "手数", reading: "てすう" }],
    romaji: "O-tesū o okake shimasu ga, nanitozo yoroshiku onegai itashimasu.",
    english: "Sorry for the trouble — thank you in advance.",
    register: "Client · humble",
    usage: "When your mail adds work for the client (forms, signatures, data).",
  },
  {
    id: "k-email-c5",
    japanese: "引き続きどうぞよろしくお願いいたします。",
    ruby: [{ text: "引", reading: "ひ" }, { text: "続", reading: "つづ" }],
    romaji: "Hikitsuzuki dōzo yoroshiku onegai itashimasu.",
    english: "Thank you for your continued cooperation.",
    register: "Client · polite",
    usage: "Ongoing projects; safe default when unsure.",
  },
];

const phonePhrases: WorkPhrase[] = [
  {
    id: "k-phone-1",
    japanese: "お電話ありがとうございます。株式会社〇〇の〇〇でございます。",
    ruby: [{ text: "電話", reading: "でんわ" }],
    romaji: "O-denwa arigatō gozaimasu. Kabushiki gaisha ○○ no ○○ de gozaimasu.",
    english: "Thank you for calling — this is ○○ of ○○ Co., Ltd.",
    register: "Client · humble",
    usage: "Inbound answer; state company then your name.",
  },
  {
    id: "k-phone-2",
    japanese: "〇〇をお願いしたく、お電話いたしました。",
    romaji: "○○ o onegai shitaku, o-denwa itashimashita.",
    english: "I am calling to ask regarding ○○.",
    register: "Client · humble",
    usage: "Outbound after they pick up; replace お電話 with ご連絡 in mail.",
  },
  {
    id: "k-phone-3",
    japanese: "担当の者におつなぎいただけますでしょうか。",
    ruby: [{ text: "担当", reading: "たんとう" }, { text: "者", reading: "もの" }],
    romaji: "Tantō no mono ni o-tsunagi itadakemasu deshō ka.",
    english: "Could you connect me to the person in charge?",
    register: "Client · humble",
    usage: "Reception call; if you know the name, add 「〇〇様はいらっしゃいますでしょうか。」",
  },
  {
    id: "k-phone-4",
    japanese: "少々お待ちください。",
    ruby: [{ text: "少々", reading: "しょうしょう" }],
    romaji: "Shōshō omachi kudasai.",
    english: "Please hold for a moment.",
    register: "Internal · polite (です・ます)",
    usage: "When transferring — say before putting on hold, not after.",
  },
];

const requestPhrases: WorkPhrase[] = [
  {
    id: "k-req-1",
    japanese: "〇〇についてご確認いただけますでしょうか。",
    ruby: [{ text: "確認", reading: "かくにん" }],
    romaji: "○○ ni tsuite go-kakunin itadakemasu deshō ka.",
    english: "Could you please confirm ○○?",
    register: "Internal · humble (team / upward)",
    usage: "Safer than 確認してください upward; neutral with peers.",
  },
  {
    id: "k-req-2",
    japanese: "ご都合のよろしい日時をお知らせいただけますでしょうか。",
    ruby: [{ text: "都合", reading: "つごう" }],
    romaji: "Go-tsugō no yoroshii nichiji o o-shirase itadakemasu deshō ka.",
    english: "Could you let me know a convenient date and time?",
    register: "Client · humble",
    usage: "Scheduling with external parties.",
  },
  {
    id: "k-req-3",
    japanese: "差し支えなければ、〇〇を共有いただけますでしょうか。",
    ruby: [{ text: "差", reading: "さ" }, { text: "支", reading: "つ" }],
    romaji: "Sashitsukae nakereba, ○○ o kyōyū itadakemasu deshō ka.",
    english: "If it is all right, could you share ○○?",
    register: "Internal · polite (です・ます)",
    usage: "Asking for a file or document without sounding demanding.",
  },
  {
    id: "k-req-4",
    japanese: "恐れ入りますが、ご検討のほどお願い申し上げます。",
    ruby: [{ text: "検討", reading: "けんとう" }],
    romaji: "Osore irimasu ga, go-kentō no hodo onegai mōshiagemasu.",
    english: "Sorry to ask — please consider this.",
    register: "Client · humble",
    usage: "Proposal to client; does not assume approval.",
  },
  {
    id: "k-req-5",
    japanese: "お手数ですが、〇〇のご対応をお願いできますでしょうか。",
    ruby: [{ text: "対応", reading: "たいおう" }],
    romaji: "O-tesū desu ga, ○○ no go-taiō o onegai dekimasu deshō ka.",
    english: "Sorry for the trouble — could I ask you to handle ○○?",
    register: "Internal · humble (team / upward)",
    usage: "Cross-team request; name deadline in the next line.",
  },
];

const apologisePhrases: WorkPhrase[] = [
  {
    id: "k-apol-1",
    japanese: "大変申し訳ございません。",
    ruby: [{ text: "申", reading: "もう" }, { text: "訳", reading: "わけ" }],
    romaji: "Taihen mōshiwake gozaimasen.",
    english: "I am very sorry.",
    register: "Client · humble",
    usage: "Serious mistake to client; do not overuse for tiny delays.",
  },
  {
    id: "k-apol-2",
    japanese: "ご迷惑をおかけし、申し訳ございません。",
    ruby: [{ text: "迷惑", reading: "めいわく" }],
    romaji: "Go-meiwaku o okake shi, mōshiwake gozaimasen.",
    english: "Sorry for the inconvenience caused.",
    register: "Client · humble",
    usage: "After a delay, wrong attachment, or missed meeting.",
  },
  {
    id: "k-apol-3",
    japanese: "重ね重ね申し訳ございません。",
    ruby: [{ text: "重", reading: "かさ" }],
    romaji: "Kasane gasane mōshiwake gozaimasen.",
    english: "I am sorry again (for repeated trouble).",
    register: "Client · humble",
    usage: "Second apology on the same issue — shows awareness.",
  },
  {
    id: "k-apol-4",
    japanese: "私の確認不足でした。以後気をつけます。",
    ruby: [{ text: "確認", reading: "かくにん" }, { text: "不足", reading: "ぶそく" }, { text: "以後", reading: "いご" }],
    romaji: "Watashi no kakunin busoku deshita. Igo ki o tsukemasu.",
    english: "It was my lack of checking. I will be careful going forward.",
    register: "Internal · polite (です・ます)",
    usage: "Own the error to your manager — avoid blaming tools or others first.",
  },
];

const thankPhrases: WorkPhrase[] = [
  {
    id: "k-thank-1",
    japanese: "ご対応ありがとうございました。",
    ruby: [{ text: "対応", reading: "たいおう" }],
    romaji: "Go-taiō arigatō gozaimashita.",
    english: "Thank you for handling that.",
    register: "Client · polite",
    usage: "After client sends data or approves — past tense.",
  },
  {
    id: "k-thank-2",
    japanese: "迅速なご返信ありがとうございます。",
    ruby: [{ text: "迅速", reading: "じんそく" }, { text: "返信", reading: "へんしん" }],
    romaji: "Jinsoku na go-henshin arigatō gozaimasu.",
    english: "Thank you for your quick reply.",
    register: "Client · respectful (相手を高める)",
    usage: "Elevates their action; good after fast client turnaround.",
  },
  {
    id: "k-thank-3",
    japanese: "お力をお借りしました。",
    ruby: [{ text: "力", reading: "ちから" }, { text: "借", reading: "か" }],
    romaji: "O-chikara o okari shimashita.",
    english: "I borrowed your strength — thank you for your help.",
    register: "Internal · humble (team / upward)",
    usage: "After a senior saves your project; spoken or short mail.",
  },
  {
    id: "k-thank-4",
    japanese: "本日は貴重なお時間をいただき、ありがとうございました。",
    ruby: [{ text: "貴重", reading: "きちょう" }],
    romaji: "Honjitsu wa kichō na o-jikan o itadaki, arigatō gozaimashita.",
    english: "Thank you for your valuable time today.",
    register: "Client · humble",
    usage: "End of meeting mail — standard and safe.",
  },
];

const reportPhrases: WorkPhrase[] = [
  {
    id: "k-rep-1",
    japanese: "〇〇の件、以下のとおり完了いたしました。",
    ruby: [{ text: "以下", reading: "いか" }, { text: "完了", reading: "かんりょう" }],
    romaji: "○○ no ken, ika no tōri kanryō itashimashita.",
    english: "Regarding ○○, it has been completed as below.",
    register: "Internal · humble (team / upward)",
    usage: "Report mail opening; bullet the facts next.",
  },
  {
    id: "k-rep-2",
    japanese: "現状、〇〇でございます。",
    ruby: [{ text: "現状", reading: "げんじょう" }],
    romaji: "Genjō, ○○ de gozaimasu.",
    english: "The current situation is ○○.",
    register: "Client · humble",
    usage: "Status to client — neutral, no blame language.",
  },
  {
    id: "k-rep-3",
    japanese: "進捗は〇％でございます。",
    ruby: [{ text: "進捗", reading: "しんちょく" }],
    romaji: "Shinchoku wa ○ pāsento de gozaimasu.",
    english: "Progress is at ○ percent.",
    register: "Internal · humble (team / upward)",
    usage: "Weekly report; add blockers in the next line.",
  },
  {
    id: "k-rep-4",
    japanese: "問題が発生しておりますので、ご相談させていただけますでしょうか。",
    ruby: [{ text: "問題", reading: "もんだい" }, { text: "発生", reading: "はっせい" }, { text: "相談", reading: "そうだん" }],
    romaji: "Mondai ga hassei shite orimasu node, go-sōdan sasete itadakemasu deshō ka.",
    english: "A problem has occurred — may I consult with you?",
    register: "Internal · humble (team / upward)",
    usage: "報連相 の 相 — ask before the client hears it elsewhere.",
  },
];

export const keigoPage: WorkPageContent = {
  slug: "keigo",
  title: "Keigo in practice",
  glyph: "敬",
  description: "Daily formulas for mail, phone, requests, apologies, thanks, and reports — not grammar theory.",
  intro:
    "Business keigo is less about memorising rules than about fixed pairs: humble language lowers your side, respectful language raises the other. Below are formulas people actually send — with register labelled so you do not mix internal and client language.",
  concepts: [
    {
      id: "kenjou",
      title: "Humble vs respectful — what to lower",
      ruby: { kanji: "謙譲語", reading: "けんじょうご" },
      romaji: "kenjōgo",
      summary:
        "Use humble forms for your actions (伺います, 申し上げます, いただきます). Use respectful forms for their actions (ご確認, お送りいただく, いらっしゃいます).",
      whatToDo: [
        "To a client, never use 見る about their document — use ご覧いただく for them viewing yours.",
        "About your own company to a client, use humble: 当社では…と存じます.",
        "Internal upward mail: humble is safe; internal peers: plain polite is often enough.",
        "When unsure with a client, choose humble — overdressed beats rude.",
      ],
    },
    {
      id: "sonkei",
      title: "Respectful language for their side",
      ruby: { kanji: "尊敬語", reading: "そんけいご" },
      romaji: "sonkeigo",
      summary: "Respectful verbs honour the other person: おっしゃる, ご覧になる, お越しになる.",
      whatToDo: [
        "Quote a client manager with おっしゃっていただいた通り in mail.",
        "Avoid あなたが言った in client mail — use ご指摘のとおり.",
        "Do not use respectful forms about yourself — it sounds arrogant or confused.",
      ],
    },
  ],
  phrases: [],
  phraseSections: [
    { title: "Email — opening", phrases: emailOpenInternal },
    { title: "Email — closing", phrases: emailCloseInternal },
    { title: "Phone", phrases: phonePhrases },
    { title: "Requesting", phrases: requestPhrases },
    { title: "Apologising", phrases: apologisePhrases },
    { title: "Thanking", phrases: thankPhrases },
    { title: "Reporting", phrases: reportPhrases },
  ],
  doDont: {
    do: [
      "Copy the whole formula first; swap only the 〇〇 slots.",
      "Match register to audience before sending.",
      "Read mail aloud once — wrong keigo is easier to hear than to see.",
    ],
    dont: [
      "Use お疲れ様です to a client unless they used it first.",
      "Use 尊敬語 for your own actions (「私がおっしゃいます」).",
      "Mix casual internal chat phrases into client mail because they feel friendly.",
    ],
  },
  sources: [
    "Agency for Cultural Affairs — keigo reference materials (尊敬語・謙譲語・丁寧語).",
    "Fixed business mail templates in ビジネスメールの書き方 standard references.",
    "Phrases verified against native business correspondence patterns (no machine-generated Japanese).",
  ],
};
